$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $root

$outDir = Join-Path $root 'dist'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$zip = Join-Path $outDir 'champions-roku.zip'
if (Test-Path $zip) { Remove-Item -Force $zip }

# Roku expects a flat zip with manifest at the root.
# Build into a clean staging folder so we don't ship dev-only files.
$stage = Join-Path $outDir 'stage'
if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
New-Item -ItemType Directory -Force -Path $stage | Out-Null

Copy-Item -Force (Join-Path $root 'manifest') $stage
Copy-Item -Recurse -Force (Join-Path $root 'source') $stage
Copy-Item -Recurse -Force (Join-Path $root 'components') $stage

$secretsDir = Join-Path $root '.secrets'
$stageSource = Join-Path $stage 'source'

function Get-SecretValue([string]$name) {
  $inPath = Join-Path $secretsDir $name
  if (-not (Test-Path $inPath)) { return "" }
  $v = (Get-Content -Raw $inPath).Trim()
  if ([string]::IsNullOrWhiteSpace($v)) { return "" }
  return $v
}

function Escape-BrsString([string]$s) {
  if ($null -eq $s) { return "" }
  # BrightScript uses doubled quotes inside "..." strings.
  return $s.Replace('"', '""')
}

$token = Get-SecretValue 'gateway_app_token.txt'
$apiBase = Get-SecretValue 'api_base.txt'

$secretsBrs = @"
' AUTO-GENERATED by scripts/package.ps1.
' DO NOT COMMIT the packaged output. This file is injected into the ZIP only.

function bundledAppToken() as String
  return "$(Escape-BrsString $token)"
end function

function bundledApiBase() as String
  return "$(Escape-BrsString $apiBase)"
end function
"@

Set-Content -Path (Join-Path $stageSource 'secrets.brs') -Value $secretsBrs -NoNewline -Encoding utf8
if ($token) { Write-Host 'Injected secret: bundledAppToken()' }
if ($apiBase) { Write-Host 'Injected secret: bundledApiBase()' }

$stageImages = Join-Path $stage 'images'
New-Item -ItemType Directory -Force -Path $stageImages | Out-Null
Get-ChildItem (Join-Path $root 'images') -File | Where-Object {
  $_.Name -notin @('.gitkeep', 'logo_src.png')
} | ForEach-Object {
  Copy-Item -Force $_.FullName $stageImages
}

# IMPORTANT: Roku expects ZIP entry paths like "source/main.brs" (forward slashes).
# PowerShell's Compress-Archive writes backslashes in entry names on Windows, which
# causes Roku to fail with: Script directory "/source" does not exist in plugin.
& tar.exe -a -c -f $zip -C $stage manifest source components images
if ($LASTEXITCODE -ne 0) {
  throw "tar.exe failed to create $zip (exit=$LASTEXITCODE)"
}

Remove-Item -Recurse -Force $stage
Write-Host "OK: $zip"
